steps:
- name: gradle:jdk17-alpine
  entrypoint: gradle
  args: ['build']
- name: 'gcr.io/cloud-builders/docker'
  env:
  - "TAG_NAME=$TAG_NAME"
  args: ['build', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/timezone/timezone:$TAG_NAME', '.']
  secretEnv: ['SPRING_DATASOURCE_USERNAME', 'SPRING_DATASOURCE_PASSWORD', 'SPRING_CLOUD_GCP_SQL_DATABASE_NAME', 'SPRING_CLOUD_GCP_SQL_INSTANCE_CONNECTION_NAME', 'SPRING_DATASOURCE_URL']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/timezone-datasource-username/versions/1
    env: "SPRING_DATASOURCE_USERNAME"
  - versionName: projects/$PROJECT_ID/secrets/timezone-datasource-password/versions/1
    env: "SPRING_DATASOURCE_PASSWORD"
  - versionName: projects/$PROJECT_ID/secrets/timezone-datasource-database-name/versions/1
    env: "SPRING_CLOUD_GCP_SQL_DATABASE_NAME"
  - versionName: projects/$PROJECT_ID/secrets/timezone-datasource-database-connection-name/versions/1
    env: "SPRING_CLOUD_GCP_SQL_INSTANCE_CONNECTION_NAME"
  - versionName: projects/$PROJECT_ID/secrets/timezone-datasource-url/versions/1
    env: "SPRING_DATASOURCE_URL"

